### ISSUE TITLE
Exceptions thrown when used in a third-party iframe with third-party cookies disabled

### ISSUE THREAD

**Issue by cdauth** [digitalfortress-tech/localstorage-slim#27]
### What happened?

I'm using the library in a cross-origin iframe while having third-party cookies disabled in Chrome.

In this situation, attempting to access the `localStorage` global variable results in the following exception: `Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

This library does not catch this exception. The fallback to memory store is never reached, because that is only enabled on an exception during `localStorage.getItem()`, which is never reached. Furthermore, `isInit` is set to `true` before the exception is thrown, causing `storage` to be `undefined`, resulting in subsequent exceptions such as `Cannot read properties of undefined (reading 'getItem')`.

### Affected version

Latest

### Reproduction URL

https://codepen.io/niketpathak/pen/WNMKzoJ

### How to reproduce?

Can be reproduced with the default Codepen while having third-party cookies disabled in Chrome. Typing something into the text field will raise errors in the browser console, and the value never makes it into the storage.

### Browsers

Chrome

**Comment by niketpathak** [comment]
Thank you for reporting this and also for your PR. Fixed in 2763131ce47d5a7a6826b6a25d555d589e4ca7dc.
